CREATE TABLE IF NOT EXISTS players (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    rating INT NOT NULL DEFAULT 1500,
    last_active TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
); 